In [139]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pltd
import seaborn as sns

In [140]:
df_data = pd.read_csv('https://drive.google.com/uc?export=download&id=1tdnYgbK3-OJeeMK-QrW-ha6WgXcC79hE', low_memory=False, encoding='latin-1')
df_data_by_artist = pd.read_csv('https://drive.google.com/uc?export=download&id=1oPnKdpQLK7CO5rUVrMwvTvQuBGSmvRLH', low_memory=False, encoding='latin-1')
df_data_by_genres = pd.read_csv('https://drive.google.com/uc?export=download&id=12lqn5lD6x5Yh6mezlg6TQ60YA-Pn8aeV', low_memory=False, encoding='latin-1')
df_data_by_year = pd.read_csv('https://drive.google.com/uc?export=download&id=1zZrUYorbuT5MTCrzqvJDiK-W4M48IrM_', low_memory=False, encoding='latin-1')
df_data_w_genres = pd.read_csv('https://drive.google.com/uc?export=download&id=1fDUFtB5CG4MBnfj80q2h9r47Nlwzy9t1', low_memory=False, encoding='latin-1')

#Foi analisado que apenas o dataframe df_data possui os nomes das músicas. O que é necessário para a indicação
#Assim trabalharemos apenas com ele no momento

In [141]:
df_data.head(2)

valence  year  acousticness  \
0   0.0594  1921         0.982   
1   0.9630  1921         0.732   

                                             artists  danceability  \
0  ['Sergei Rachmaninoff', 'James Levine', 'Berli...         0.279   
1                                     ['Dennis Day']         0.819   

   duration_ms  energy  explicit                      id  instrumentalness  \
0       831667   0.211         0  4BJqT0PrAfrxzMOxytFOIz             0.878   
1       180533   0.341         0  7xPhfUan2yNtyFG0cUWkt8             0.000   

   key  liveness  loudness  mode  \
0   10     0.665   -20.096     1   
1    7     0.160   -12.441     1   

                                                name  popularity release_date  \
0  Piano Concerto No. 3 in D Minor, Op. 30: III. ...           4         1921   
1                            Clancy Lowered the Boom           5         1921   

   speechiness   tempo  
0       0.0366  80.954  
1       0.4150  60.936

In [142]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int64  
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  object 
 4   danceability      170653 non-null  float64
 5   duration_ms       170653 non-null  int64  
 6   energy            170653 non-null  float64
 7   explicit          170653 non-null  int64  
 8   id                170653 non-null  object 
 9   instrumentalness  170653 non-null  float64
 10  key               170653 non-null  int64  
 11  liveness          170653 non-null  float64
 12  loudness          170653 non-null  float64
 13  mode              170653 non-null  int64  
 14  name              170653 non-null  object 
 15  popularity        170653 non-null  int64  
 16  release_date      17

In [143]:
#df_data_by_artist.query('key == 10')
valores_distintos = df_data.query('key == key')['key'].unique()
np.sort(valores_distintos)

#Aparentemente a coluna key é a nota das músicas, que varia de 0 a 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
valores_distintos = df_data.query('popularity == popularity')['popularity'].unique()
np.sort(valores_distintos)

#Aparentemente a coluna popularity é a popularidade das músicas, que varia de 0 a 100

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  99, 100])

In [145]:
valores_distintos = df_data.query('explicit == explicit')['explicit'].unique()
np.sort(valores_distintos)

array([0, 1])

In [146]:
df_data['name'].value_counts()

White Christmas                    73
Winter Wonderland                  63
Summertime                         56
Jingle Bells                       53
Overture                           46
                                   ..
I'd Rather Die Young                1
Oh Baby Doll                        1
Music To Be Murdered By             1
The Blues Are Brewin'               1
Billetes Azules (with J Balvin)     1
Name: name, Length: 133638, dtype: int64

In [147]:
df_data.query('name == "White Christmas"').head(3)

valence  year  acousticness  \
2842   0.0486  1936         0.995   
4006   0.2470  1942         0.673   
4527   0.2250  1944         0.905   

                                                artists  danceability  \
2842                                    ['Harry James']         0.211   
4006  ['Bing Crosby', 'Ken Darby Singers', 'John Sco...         0.317   
4527                                   ['The Meltones']         0.409   

      duration_ms  energy  explicit                      id  instrumentalness  \
2842       197360  0.0653         0  6K8aoScBFtdQjqCQqA1LDY          0.875000   
4006       177480  0.1580         0  4so0Wek9Ig1p6CRCHuINwW          0.353000   
4527       193373  0.2630         0  7E0KaPMjaU0f6MgH8DKeMh          0.000647   

      key  liveness  loudness  mode             name  popularity release_date  \
2842    2     0.107   -24.009     1  White Christmas          14         1936   
4006    9     0.338   -16.485     1  White Christmas          76   1942-01-01   
4527    5     0.272   -10.080     1  White Christmas           6   1944-06-14   

      speechiness    tempo  
2842       0.0414  133.594  
4006       0.0381  130.503  
4527       0.0258   84.126

In [148]:
df_data['chave'] = df_data['name'] + df_data['artists']

In [150]:
name_artist = ['name','artists']
df_data = df_data.drop_duplicates(subset=name_artist,keep='last')


In [151]:
#uma música pode ser tocada por mais de um artista, assim, agruparemos o dataset por média das características das músicas

#df = df_data.groupby(['name','acousticness', 'danceability', 'energy', 'instrumentalness', 'liveness', 'loudness', 'popularity', 'speechiness','valence'])['valence'].agg(['mean'])

In [152]:
#df = df_data[['id','acousticness','danceability','energy','instrumentalness', 'liveness', 'loudness', 'popularity', 'speechiness','valence']]
df = df_data[['acousticness','danceability','energy','instrumentalness', 'liveness', 'loudness', 'speechiness','valence']]

In [153]:
df

acousticness  danceability  energy  instrumentalness  liveness  \
1            0.73200         0.819   0.341          0.000000    0.1600   
2            0.96100         0.328   0.166          0.913000    0.1010   
3            0.96700         0.275   0.309          0.000028    0.3810   
4            0.95700         0.418   0.193          0.000002    0.2290   
5            0.57900         0.697   0.346          0.168000    0.1300   
...              ...           ...     ...               ...       ...   
170648       0.08460         0.786   0.808          0.000289    0.0822   
170649       0.20600         0.717   0.753          0.000000    0.1010   
170650       0.10100         0.634   0.858          0.000009    0.2580   
170651       0.00998         0.671   0.623          0.000008    0.6430   
170652       0.13200         0.856   0.721          0.004710    0.1820   

        loudness  speechiness  valence  
1        -12.441       0.4150   0.9630  
2        -14.850       0.0339   0.0394  
3         -9.316       0.0354   0.1650  
4        -10.096       0.0380   0.2530  
5        -12.506       0.0700   0.1960  
...          ...          ...      ...  
170648    -3.702       0.0881   0.6080  
170649    -6.020       0.0605   0.7340  
170650    -2.226       0.0809   0.6370  
170651    -7.161       0.3080   0.1950  
170652    -4.928       0.1080   0.6420  

[157685 rows x 8 columns]

In [154]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# create input vector as a row in a dataframe
input_vector = pd.DataFrame([[0.98200,	0.279,	0.211,	0.878000,	0.6650,	-20.096,	0.0366,	0.0594]])

# calculate cosine similarity between input vector and each row in the dataframe
cosine_similarities = cosine_similarity(df, input_vector)

# add cosine similarity column to the dataframe
df['cosine_similarity'] = cosine_similarities



<ipython-input-154-884c4b473ba8>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cosine_similarity'] = cosine_similarities


In [164]:
df_retorno = df.sort_values('cosine_similarity',ascending=False).head(10)

In [167]:
df_retorno.merge(df_data[['id','name','artists']],how = 'inner',left_index=True,right_index=True)

acousticness  danceability  energy  instrumentalness  liveness  \
39             0.982         0.279  0.2110             0.878     0.665   
76360          0.964         0.214  0.1540             0.894     0.679   
156253         0.952         0.225  0.2370             0.826     0.652   
156029         0.993         0.240  0.1070             0.905     0.697   
1677           0.933         0.288  0.1450             0.760     0.717   
61238          0.988         0.389  0.1800             0.875     0.684   
113664         0.928         0.217  0.2610             0.798     0.714   
1633           0.982         0.295  0.0713             0.891     0.699   
1631           0.975         0.370  0.1890             0.842     0.694   
95608          0.929         0.119  0.2090             0.884     0.648   

        loudness  speechiness  valence  cosine_similarity  \
39       -20.096       0.0366   0.0594           1.000000   
76360    -20.011       0.0324   0.0389           0.999989   
156253   -18.808       0.0440   0.1140           0.999988   
156029   -20.576       0.0397   0.0396           0.999983   
1677     -19.411       0.0359   0.0798           0.999976   
61238    -19.482       0.0385   0.0430           0.999976   
113664   -19.097       0.0890   0.0920           0.999975   
1633     -20.649       0.0472   0.0379           0.999973   
1631     -22.010       0.0442   0.0734           0.999968   
95608    -19.103       0.0366   0.0397           0.999967   

                            id  \
39      1SCWBjhk5WmXPxhDduD3HM   
76360   4exmbinJUBL4qaM4fPzN9y   
156253  6munOuNriTf09mrAzjqrhY   
156029  5bZfpv8Pw7Qe41KETBCeSZ   
1677    7paJusVgjTQGvFZpTDHYBW   
61238   6CyXhqucG8gi7K8hqEWqTO   
113664  6nl4q6ukiqrliQt6larrph   
1633    34y6Gie19NTeapGMoqCHhl   
1631    19Ol0MHJQ9aFXy1k1717Yq   
95608   30NBz8B4fmPQgks9zrhd5Q   

                                                     name  \
39      Piano Concerto No. 3 in D Minor, Op. 30: III. ...   
76360   Concert for piano and orchestra: III. Phantais...   
156253  Stravinsky: Le sacre du printemps (The Rite of...   
156029               Polonaise-Fantaisie in A-Flat, Op.61   
1677    Sonata for Piano in B Minor, S. 178: III. Alle...   
61238                          Piano Sonata No. 5, Op. 53   
113664                   The Flowermarket* - Instrumental   
1633    Années de pèlerinage, Première année (Suis...   
1631                         Mephisto Waltz No. 1, S. 514   
95608     Ein Heldenleben, Op. 40: The Hero's Adversaries   

                                                  artists  
39      ['Sergei Rachmaninoff', 'James Levine', 'Berli...  
76360                   ['Howard Shelly', 'Kurt Graunke']  
156253              ['Igor Stravinsky', 'Eugene Ormandy']  
156029            ['Frédéric Chopin', 'William Kapell']  
1677                 ['Franz Liszt', 'Vladimir Horowitz']  
61238         ['Alexander Scriabin', 'Vladimir Horowitz']  
113664                                  ['André Previn']  
1633                 ['Franz Liszt', 'Vladimir Horowitz']  
1631                 ['Franz Liszt', 'Vladimir Horowitz']  
95608                 ['Richard Strauss', 'Fritz Reiner']